name: web

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  json_rpc_2: ^2.1.0
  web_socket_channel: ^1.1.0

dev_dependencies:
  build_runner: ^1.8.0
  build_web_compilers: ^2.9.0
  pedantic: ^1.9.0
